#! /bin/sh

sxhkd &

bspc monitor -d term web emacs code music chat files extra

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color #eeaaaa

xrdb -merge ~/.Xresources &
compton &
polybar top &
feh --bg-scale ~/.wallpaper.png &
